### PR TITLE
creating model framework

### LINKED ISSUE #7: text processing & model scaffolding

### PR DESCRIPTION
**Pull request by claireboyd**
standardizing some of the framework between jack's bert model & my code from friday

### CODE REVIEW

**Comment by claireboyd** [comment]
Updates:
* created custom datasets/dataloaders as well as training/functions etc to work across all models
* pipeline seems to be working

What isn't working:
* model structure is off for the ones I've made (can talk more about this) so we can divide up the models and use the dataloaders to experiment with which ones can work best.

**Comment by claireboyd** [comment]
@jgibson517 or anyone else - if this looks good to you, we can merge into main before we collab tonight!

**Comment by jgibson517** [comment]
@claireboyd  do we want to combine our ReviewDataset classes, they should be basically the same expect in the tokenizer and the label class, the BERT model takes [0,1] and [1,0] vs 0, 1.

**Comment by claireboyd** [comment]
@jgibson517  yeah sure! i need to pivot to other stuff until we meet but one of us can combine them tonight/tomorrow

**Comment by claireboyd** [comment]
also i should change it so it just takes it a built tokenizer and doesn't need to build it within the class - i went back and forth on that but especially if we are using the same across both then that design makes more sense

**Pull request merged**
